apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-app
  labels:
    app: kubernetes-app
spec:
  containers:
  - image: busybox
    name: kubernetes-app
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
